integration:
  server:
    host: usermanagement.adobe.io
    endpoint: /v2/usermanagement
    ims_host: ims-na1.adobelogin.com
    ims_endpoint_jwt: /ims/exchange/jwt

  enterprise:
    org_id: [ORG ID]
    api_key: [API KEY]
    client_secret: [CLIENT SECRET]
    tech_acct: [TECH ACCT ID]
    priv_key_path: /path/to/private.key

domains:
  example.com:
    type: [enterpriseID or federatedID]
    ldap:
      username: [LDAP USER]
      pw: [LDAP PASSWORD]
      host: [LDAP HOST]
      base_dn: DC=example,DC=com
      fltr: (&(objectClass=user)(objectCategory=person)(memberOf=%(groupdn)s)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
      # set to True if you want to validate SSL cert
      require_tls_cert: False
    groups:
      # example group mapping
      - directory_group: AdobeCC-All #Group CN
        dashboard_groups:
         - All Apps
      - directory_group: AdobeCC-Photoshop
      	dashboard_groups:
      	 - Photoshop Users

logging:
  # specifies whether you wish to generate a log file
  # 'True' or 'False'
  logToFile: True
  # output path for logs
  relativeFilePath: logs.txt
  #Logging Level: Can be "debug", "info", "warning", "error", or "critical".  This is in ascending order, meaning "debug" < "critical".  Will only be used on file log, console log is always "debug"
  level: debug