integration:
  server:
    host: usermanagement.adobe.io
    endpoint: /v2/usermanagement
    ims_host: ims-na1.adobelogin.com
    ims_endpoint_jwt: /ims/exchange/jwt

  enterprise:
    org_id: [ORG ID]
    api_key: [API KEY]
    client_secret: [CLIENT SECRET]
    tech_acct: [TECH ACCT ID]
    priv_key_path: /path/to/private.key

domains:
  example.com:
    type: [enterpriseID or federatedID]
    ldap:
      username: [LDAP USER]
      pw: [LDAP PASSWORD]
      host: [LDAP HOST]
      base_dn: DC=example,DC=com
      fltr: (&(objectClass=user)(objectCategory=person)(memberOf=%(groupdn)s)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
      # set to True if you want to validate SSL cert
      require_tls_cert: False
    groups:
      # example group mapping
      - directory_group: AdobeCC-All
        dashboard_groups:
         - All Apps
